# Generated by Django 2.2.13 on 2021-07-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0044_auto_20210714_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmembermonitor',
            name='user_org',
        ),
        migrations.AddField(
            model_name='organizationmembermonitor',
            name='user_org_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dappx.Organization'),
        ),
    ]
