# Generated by Django 2.2.13 on 2021-07-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0046_auto_20210714_0657'),
        ('dappx', '0044_organizationmember_organization'),
    ]

    operations = [
    ]
