version: '3'

services:
    db:
        restart: always
        image: postgres
        volumes:
            - /opt/var/postgres-data:/var/lib/postgresql/data
        environment:
          POSTGRES_DB: db
    project:
        build: .
        volumes:
            - ./dprojx:/home/web/pam
            - /opt/var/sock:/home/sock
        ports:
            - 8001:8001
        depends_on:
            - db
        command: /usr/local/bin/gunicorn --env DJANGO_SETTINGS_MODULE=dprojx.settings dprojx.wsgi --workers 16 --bind=unix:/home/sock/dprojx-dev.sock
        entrypoint: /entrypoint.sh
        restart: always

    web-server:
        image: nginx
        volumes:
            - ./config/nginx/site-enabled/default-dev:/etc/nginx/conf.d/default-dev.conf
            - /opt/var/sock:/home/sock
            - ./dprojx/static:/var/data/dprojx/static
            - /opt/var/certbot-etc:/etc/letsencrypt
            - /opt/var/ssl-certs:/etc/ssl/certs
            - /opt/var/certbot-var:/var/lib/letsencrypt
            - /opt/var/acme-challenge:/var/data/acme-challenge
        depends_on:
            - project
        ports:
            - 80:80
            - 443:443
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - /opt/var/certbot-etc:/etc/letsencrypt
            - /opt/var/certbot-var:/var/lib/letsencrypt
            - /opt/var/acme-challenge:/var/www/html/.well-known/acme-challenge/
