version: '3'

services:
    db:
        restart: always
        image: postgres
        volumes:
            - ../postgres-data:/var/lib/postgresql/data
        ports:
            - 5436:5432
        environment:
          POSTGRES_DB: db
    project:
        build: .
        volumes:
            - ./dprojx:/home/web/pam
            - ./sock:/home/sock
        ports:
            - 8001:8001
        depends_on:
            - db
        command: /usr/local/bin/gunicorn --env DJANGO_SETTINGS_MODULE=dprojx.settings dprojx.wsgi --workers 3 --bind=unix:/home/sock/dprojx.sock
        entrypoint: /entrypoint.sh
        restart: always

    web-server:
        image: nginx
        volumes:
            - ./config/nginx/site-enabled/default:/etc/nginx/conf.d/default.conf
            - ./sock:/home/sock
            - ./dprojx/static:/var/data/dprojx/static
            - ../certbot-etc:/etc/letsencrypt
            - ../ssl-certs:/etc/ssl/certs
            - ../certbot-var:/var/lib/letsencrypt
            - ../acme-challenge:/var/data/acme-challenge
        depends_on:
            - project
        ports:
            - 80:80
            - 443:443
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ../certbot-etc:/etc/letsencrypt
            - ../certbot-var:/var/lib/letsencrypt
            - ../acme-challenge:/var/www/html/.well-known/acme-challenge/
