version: '3'

services:
    db:
        restart: always
        image: postgres:11
        volumes:
            - ../postgres-data-prod:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: db
            POSTGRES_HOST_AUTH_METHOD: trust
    project:
        build: .
        volumes:
            - ./dprojx:/home/web/pam
            - /opt/var/media-prod-api:/home/web/pam/media
            - ./sock:/home/sock
        ports:
            - 8822:8822
        depends_on:
            - db
        command: newrelic-admin run-program /usr/local/bin/gunicorn --env DJANGO_SETTINGS_MODULE=dprojx.settings dprojx.wsgi --workers 8 --timeout 999 --bind=0.0.0.0:8822
        # command: python3 manage.py runserver 0.0.0.0:8822
        entrypoint: /entrypoint.sh
        restart: always

    web-server:
        image: nginx
        volumes:
            - ./config/nginx/site-enabled/prod.conf:/etc/nginx/conf.d/default.conf
            - ./dprojx/static:/var/data/dprojx/static
        ports:
            - 8844:80
        restart: always
