version: '3'

services:
    db:
        restart: always
        image: postgres
        volumes:
            - ../postgres-data:/var/lib/postgresql/data
        ports:
            - 5436:5432
        environment:
          POSTGRES_DB: db
    project:
        build: .
        volumes:
            - ./dprojx:/home/web/pam
            - ./sock:/home/sock
        ports:
            - 8001:8001
        depends_on:
            - db
        command: python3 manage.py runserver 0.0.0.0:8001
        entrypoint: /entrypoint.sh
        restart: always
